name = "Triple MacTusk"
author = "T Shaw Killer"
version = "1.0.1"
description = "Forces the Triple MacTusk biome to spawn during world generation."
api_version = 10
priority = -1000
dont_starve_compatible = false
reign_of_giants_compatible = false
shipwrecked_compatible = false
dst_compatible = true
client_only_mod = false
all_clients_require_mod = false
server_filter_tags = { "triple mactusk" }
forumthread = ""
icon_atlas = "triple.xml"
icon = "triple.tex"