STRINGS.NAMES.DEER_ANTLER3 = "鹿之匙"
STRINGS.NAMES.SUCCULENT_PICKED = STRINGS.NAMES.SUCCULENT_PICKED or "多肉植物"
STRINGS.NAMES.WINTER_ORNAMENT_LIGHT1 = STRINGS.NAMES.WINTER_ORNAMENT_LIGHT1 or "红色圣诞灯"
STRINGS.NAMES.WINTER_ORNAMENT_LIGHT2 = STRINGS.NAMES.WINTER_ORNAMENT_LIGHT2 or "绿色圣诞灯"
STRINGS.NAMES.WINTER_ORNAMENT_LIGHT3 = STRINGS.NAMES.WINTER_ORNAMENT_LIGHT3 or "蓝色圣诞灯"
STRINGS.NAMES.WINTER_ORNAMENT_LIGHT4 = STRINGS.NAMES.WINTER_ORNAMENT_LIGHT4 or "白色圣诞灯"

STRINGS.NAMES.SECOIN = "简单金币"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUCKAMULET = "简单金币"

STRINGS.NAMES.STEALER = "金币挖掘机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STEALER = "有精度也有硬度，又能撩又能敲"

STRINGS.NAMES.GOLDSTAFF = "点金法杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOLDSTAFF = "将一切变成金币"

STRINGS.NAMES.VIPCARD = "VIP贵宾卡"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VIPCARD = "经常花钱的必需品"

STRINGS.NAMES.LUCKAMULET = "幸运项链"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUCKAMULET = "镶嵌的水晶包裹着虔诚的祝福"

STRINGS.SIMPLEECONOMY={
[1] = "开始挣钱之旅~",
[2] = "交易",
[3] = "说明",
[4] = "返回",
[5] = "关闭",
[6] = "下一页",
[7] = "上一页",
[8] = "随机蓝图",
[9] = "金币 + ",
[10] = "金币 共+ ",
[11] = "这些东西似乎没有市场价格",
[12] = "那里没有可以变成金币的东西",
[13] = "交易等级提升!",
[14] = " 悄悄告诉你，我的存款有",
[15] = "。",
[16] = " 不要被吓死，我的存款可是有",
[17] = " 之多。",
[18] = "",
[19] = "",
}